name: Pylint and Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: todo_list
          MYSQL_USER: sahr
          MYSQL_PASSWORD: root
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        pip install mysql-connector-python
    - name: Run tests
      env:
        DB_HOST: localhost
        DB_USER: sahr
        DB_PASSWORD: root
        DB_DATABASE: todo_list
      run: |
        python -m unittest test_todo.py -v
    - name: Analyzing the code with pylint
      run: |
        pylint $(git ls-files '*.py')


    
